config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'cart/index'
get 'category/:title', to: 'static_pages#category'
  resources :menus
  #get 'static_pages/home'
  root 'static_pages#home'
  #get 'static_pages/help'
  
  get '/help' => 'static_pages#help'
  
 get '/aboutSend/:id' => 'static_pages#aboutSend'
  
  get '/about' => 'static_pages#about'
  
  get '/login', to: 'user#login'
  get '/logout', to: 'user#logout'
  
  
  get '/clearcart', to: 'cart#clearCart'
  get '/cart', to: 'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/decrease/:id' => 'cart#decrease'
  
  #root :to => 'static_pages#home'
  root :to => 'site#home'
  
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

post '/search' => 'menus#search'

  resources :orders do 
    resources:ordermenus
  end
  
  devise_for :users do 
    resources :orders
  end
  
  get '/checkout' => 'cart#createOrder'
  get '/paid/:id' => 'static_pages#paid'
  #get 'static_pages/about'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu.rb
class Menu < ApplicationRecord
    
    
    
    
    
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]
  

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

def search
     st = "%#{params[:q]}%"
     @menus = Menu.where("title like ?", st)
end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end




  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:title, :description, :price, :image, :url, :category)
   end
 



 end

                                                                                                                                                                                                                                                                                     

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<div class="mainCont">
<%= form_for(menu) do |f| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div >

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>


<div class="divC">
 </br>
 <h1> Our Yummy Products</h1>
</div>
</br>
</br>

 <% @menus.each do |menu| %>
 <div class="menuhols">
 <h1><%= menu.title %></h1>


 <%= link_to (image_tag menu.url, :class => "menuholsIm"), menu %>
 <p><%= menu.description %></p>
 <p>Price <%= number_to_currency(menu.price, :unit => "€") %>
 <br>
 Category: <%= menu.category %></p>


 
 <p>
 
 <%= link_to 'Show', menu, :class => "button", :role => "button" %>
 <% if session[:login] == 1 %> 
 <%= link_to 'Edit', edit_menu_path(menu), :class => "button", :role => "button" %>
 <%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role =>
"button" %>
<% end %>
 <% if user_signed_in? %>
 <a href="/cart/<%= menu.id %>" class="button">Add To Cart</a>
<% end %>
 </p>
 </div>
 <% end %>
</div>
<br>

<footer class="foot">
<% if session[:login] == 1 %> 
if current_user.admin?
<%= link_to 'New Menu Item', new_menu_path, :class =>"button", :role=>"button" %>
<%= link_to 'New Category', new_category_path, :class =>"button", :role=>"button"  %>
<% end %>
</footer>

app/views/menus/new.html.erb
<h1>New Product</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/search.html.erb
<h2>You Searched Our Product Catalog For <%= @search_term %></h2>

<% if @menus.length ==0  %>
<br />
<h2>No products were found to match your search</h2>
<% end %>

<table class="catalog">
  <% @menus.each do |menu| %>
      <tr>
        <td>
          <div class="image">
            <%= link_to (image_tag menu.url, :style => "height:100px"), menu %>
          </div>
          <div class="title">
            <%= link_to menu.title, menu %>
          </div>
          <div class="description">
            <%= menu.description %>
          </div>  
          <div class="price">
             <%= number_to_currency(menu.price, :unit => "€") %>
          </div>
          <div class="links">
            <% if user_signed_in? %>
              <%= link_to 'Edit', edit_menu_path(menu) %>
              <%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%else%>
            
              <a href="/cart/<%= menu.id %>">Add to Cart</a>
            <%end%> 
            </br>
        </div>
        </td>
      </tr>
    <% end %>
</table>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>




 <div id="menusContainer">
   <h1><%= @menu.title %></h1>
   <%= image_tag @menu.url, :class => 'welcomIm'  %>
       <h2><%= @menu.description %></h1>
   
    <div class="menuhols">
       <p>Price <%= number_to_currency(@menu.price, :unit => "€") %>
       <br>
        Category: <%= @menu.category %>
        <br>
        
       
       <p>
         <%= link_to 'Back',  menus_path, :class => "button", :role => "button" %>
         <%= link_to 'Edit',  edit_menu_path(@menu), :class => "button", :role => "button" %>
         
       </p>
        
      </div>
   
   
   </div>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>