config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'cart/index'
get 'category/:title', to: 'static_pages#category'
  resources :menus
  #get 'static_pages/home'
  root 'static_pages#home'
  #get 'static_pages/help'
  
  get '/help' => 'static_pages#help'
  
 get '/aboutSend/:id' => 'static_pages#aboutSend'
  
  get '/about' => 'static_pages#about'
  
  get '/login', to: 'user#login'
  get '/logout', to: 'user#logout'
  
  
  get '/clearcart', to: 'cart#clearCart'
  get '/cart', to: 'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/decrease/:id' => 'cart#decrease'
  
  #root :to => 'static_pages#home'
  root :to => 'site#home'
  
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

post '/search' => 'menus#search'

  resources :orders do 
    resources:ordermenus
  end
  
  devise_for :users do 
    resources :orders
  end
  
  get '/checkout' => 'cart#createOrder'
  get '/paid/:id' => 'static_pages#paid'
  #get 'static_pages/about'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_categories.html.erb
<h1>Explore the Categories</h1>

  <% @categories.each do |category| %>
             <div class="menuhols">
            <p><%= category.title %></p>
           <%= link_to (image_tag category.image, :class=>"menuholsIm"), category %>
           <p><%= category.description %></p>
    <p><a href="/category/<%= category.title %>" class="button"><%= category.title %></a></p>
     </div>
    <% end %>

app/views/layouts/_popular.html.erb
<h1>Explore Our Most Popular products</h1>
</br>

<div id="menusContainer">

  <% @menus.limit(2).order(:id).each do |menu| %>
      <tr>
        <td>
          <div class="image">
            <%= link_to (image_tag menu.url, :style => "height:100px"), menu %>
          </div>
          <div class="title">
            <%= link_to menu.title, menu %>
          </div>
          <div class="description">
            <%= menu.description %>
          </div>  
          <div class="price">
             <%= number_to_currency(menu.price, :unit => "€") %>
          </div>
          
          <div class="links">
            <% if session[:login] ==1 %>
              <%= link_to 'Edit', edit_menu_path(menu) %>
              <%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%else%>
            
              <a href="/cart/<%= menu.id %>">Add to Cart</a>
            <%end%>  
            </br>
          <br>
        </div>
        </td>
      </tr>
    <% end %>
    
</table>

app/views/layouts/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<%= label_tag(:q, "Search our products:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="footer, address, phone, icons" />
	
    <title><%= content_for(:title) ?  yield(:title): "BabyBites" %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     	 
  
  </head>

  <body>
    
     <header class="headSec">
 <h1>Baby Bites</h1>

 <ul>
 <li><%= link_to "Home", root_path %></li>
 <li><%= link_to "Milestones", help_path  %></li>
 <li><%= link_to "Menu", "/menus" %></li>
 <li><%= link_to "View Cart", "/cart" %></li>
 
                   <% if user_signed_in? %>
                 <li><a href="#">Hi <%= current_user.email %></a></li>
                  <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                 <li><%= link_to "View Orders", orders_path  %></li>
                 <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
                 <li><%= link_to 'Register', new_user_registration_path %></li> 
                 <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>


        <% if session[:login] == 1 %> 
        <li><%= link_to "Admin Logout", logout_path %></li>
        <% else %>
        
        <li><%= link_to "Admin Login", login_path %></li>
        <% end %>
 <li><%= link_to "Contact Us", about_path  %></li>
 </ul>

 </header>
 
 
 
 <div class="container">
 <%= yield %>
<%=render 'layouts/search'%>

 </div>
 
<footer class="footer-distributed">
 
			<div class="footer-left">
				<h3>About<span>BabyBites</span></h3>
 
				<p class="footer-links">
					<a href="#">Home</a>
					|
					<a href="#">Blog</a>
					|
					<a href="#">About</a>
					|
					<a href="#">Contact</a>
				</p>
 
				<p class="footer-company-name">© 2020 BabyBites</p>
			</div>
 
			<div class="footer-center">
				<div>
					<i class="fa fa-map-marker"></i>
					  <p><span>401 Maple Street road
						 St.Michaels Park</span>
						Dublin 12, Dublin, Ireland</p>
				</div>
 
				<div>
					<i class="fa fa-phone"></i>
					<p>+953 524 1534</p>
				</div>
				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:support@eduonix.com">support@baby-bitescontactemail.com</a></p>
				</div>
			</div>
			<div class="footer-right">
				<p class="footer-company-about">
					<span>About the company</span>
					We offer the highest quality nutritional food to suite all your babies needs and also offer all the information to get you the best plan.</p>
			</div>
		</footer>
	</body>
</html>